export const ROUTES = {
  INDEX: "/",
  AUTH: "/auth",
  AUTH_CALLBACK: "/auth/callback",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  REQUEST_ACCESS: "/request-access",
  ACCESS_PENDING: "/access-pending",
  CONVERSATIONS: "/conversations",
  CONVERSATION: "/conversation",
  CONVERSATIONS_DETAIL: "/conversations/:id",
  ASSISTANT_CHAT: "/assistant",
  CONVERSATION_ASSISTANT: "/assistant",
  SETTINGS: "/settings",
  SETTINGS_APPEARANCE: "/settings/appearance",
  SETTINGS_AGENTS: "/settings/agents",
  SETTINGS_AGENTS_DETAIL: "/settings/agents/:id",
  SETTINGS_CUSTOM_TABLES: "/settings/custom-tables",
  SETTINGS_CUSTOM_TABLES_DETAIL: "/settings/custom-tables/:id",
  NOT_FOUND: "*",
};
