
project_id = "zgtukvtbfucrvdpicvxx"

[functions.ai-chat]
verify_jwt = false

[functions.voice-chat]
verify_jwt = false

[functions.ai-chat-v2]
verify_jwt = false

[functions.wss-functions]
verify_jwt = false

[functions.custom-table-data]
verify_jwt = false

[functions.table-builder]
verify_jwt = false

[functions.test]
verify_jwt = false
