import { EventEmitter } from "events";

export const AgentEventEmitter = new EventEmitter();

export const EVENTS = {
  CONNECTED: "CONNECTED",
  DISCONNECTED: "DISCONNECTED",
  ERROR: "ERROR",
  MESSAGE: "MESSAGE",
  AGENT_IS_TALKING: "AGENT_IS_TALKING",
  AGENT_RESPONSE_DELTA: "AGENT_RESPONSE_DELTA",
  AGENT_RESPONSE_DONE: "AGENT_RESPONSE_DONE",
  USER_TRANSCRIPTION_DELTA: "USER_TRANSCRIPTION_DELTA",
  USER_TRANSCRIPTION_DONE: "USER_TRANSCRIPTION_DONE",
  CONVERSATION_ITEM_CREATED: "CONVERSATION_ITEM_CREATED",
  CONTEXT_UPDATED: "CONTEXT_UPDATED",
};

export default AgentEventEmitter;
