export const EVENTS = {
  OUTPUT_AUDIO_BUFFER_STARTED: "output_audio_buffer.started",
  OUTPUT_AUDIO_BUFFER_STOPPED: "output_audio_buffer.stopped",
  RESPONSE_AUDIO_TRANSCRIPT_DELTA: "response.audio_transcript.delta",
  RESPONSE_AUDIO_TRANSCRIPT_DONE: "response.audio_transcript.done",
  RESPONSE_CREATED: "response.created",
  RESPONSE_UPDATED: "response.updated",
  RESPONSE_FINISHED: "response.finished",
  RESPONSE_DONE: "response.done",
  RESPONSE_ERROR: "response.error",
  RESPONSE_CANCELLED: "response.cancelled",
  CONVERSATION_DELTA: "conversation.item.input_audio_transcription.delta",
  CONVERSATION_DONE: "conversation.item.input_audio_transcription.completed",
  ASSISTANT_RESPONSE_DELTA: "response.audio_transcript.delta",
  ASSISTANT_RESPONSE_DONE: "response.audio_transcript.done",
  FUNCTION_CALL_ARGUMENTS_DONE: "response.function_call_arguments.done",
};
