// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseUrl, getSupabaseKey } from "@/utils/supabaseUtils";

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY = getSupabaseKey();

export const dynamicHeaders = {
  "x-tenant-id": null, // start empty
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      fetch: (url, options) => {
        const originalHeaders =
          options.headers instanceof Headers
            ? Object.fromEntries(options.headers.entries())
            : options.headers || {};

        options.headers = {
          ...originalHeaders,
          ...(dynamicHeaders["x-tenant-id"]
            ? { "x-tenant-id": dynamicHeaders["x-tenant-id"] }
            : {}),
        };
        return fetch(url, options);
      },
    },
  }
);
