// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgtukvtbfucrvdpicvxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndHVrdnRiZnVjcnZkcGljdnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDQ3NzQsImV4cCI6MjA1MzY4MDc3NH0.3xvkpYoRUFhdVYa2GylvfmxGp-XYrpsdfausI4JqiQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);