// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseUrl } from "@/utils/supabaseUtils";

const SUPABASE_URL = getSupabaseUrl();
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpndHVrdnRiZnVjcnZkcGljdnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxMDQ3NzQsImV4cCI6MjA1MzY4MDc3NH0.3xvkpYoRUFhdVYa2GylvfmxGp-XYrpsdfausI4JqiQk";

export const dynamicHeaders = {
  "x-tenant-id": null, // start empty
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      fetch: (url, options) => {
        const originalHeaders =
          options.headers instanceof Headers
            ? Object.fromEntries(options.headers.entries())
            : options.headers || {};

        options.headers = {
          ...originalHeaders,
          ...(dynamicHeaders["x-tenant-id"]
            ? { "x-tenant-id": dynamicHeaders["x-tenant-id"] }
            : {}),
        };
        console.log("options", options.headers.Authorization);
        return fetch(url, options);
      },
    },
  }
);
